### ISSUE TITLE
Network configuration

### ISSUE THREAD

**Issue by ss0028** [pihomeserver/Kupiki-Hotspot-Script#103]
### Actual behavior
what should we replace for:
HOTSPOT_IP="?"
HOTSPOT_NETWORK="?"
There was no login page with our configuration.
###LOGS
[pihotspot.log](https://github.com/pihomeserver/Kupiki-Hotspot-Script/files/1906937/pihotspot.log)

![img_20180413_154530](https://user-images.githubusercontent.com/31015605/38730005-9267e3c6-3f32-11e8-8f1c-c4e02fe5d3c0.jpg)
![img_20180413_154550](https://user-images.githubusercontent.com/31015605/38730046-b6b3f0e4-3f32-11e8-9b2d-b583c3fc00a5.jpg)

please help me asap.

**Comment by pihomeserver** [comment]
IP of the exposed Hotspot and IP of the network that will be used for the devices on the hotspot
Must be different than the network used on the eth0 interface

In you case try
HOTSPOT_IP="192.168.10.1"
HOTSPOT_NETWORK="192.168.10.0"

**Comment by R3apeR25** [comment]
okay thank you very much for your time.

but, one last problem . Can't log in, i've added user from dalaradius and verified from database, but getting this error while logging in.


![dd](https://user-images.githubusercontent.com/38279152/38751039-787ca798-3f74-11e8-89f3-1dd8c0180cee.PNG)

**Comment by pihomeserver** [comment]
try to ping the 192.168.10.1 from your raspberry. Also check that coova service is up and running

**Comment by ss0028** [comment]
Thankyou, now it works.
