### ISSUE TITLE
X11 stopped working over SSH after install 

### ISSUE THREAD

**Issue by darkprince1337** [pihomeserver/Kupiki-Hotspot-Script#109]
X11 was working before installing hotspot.  I lost remote X-programs access after install kupiki. Now only SSH is working and i'm getting error following error on opening GUI apps over ssh.
`Error: Can't open display:`

PS: Xauth , Xorg is properly installed.
and i tried 
```
pi@CodeGimmicksNET:~ $ xclock
Error: Can't open display:
pi@CodeGimmicksNET:~ $ echo $DISPLAY

pi@CodeGimmicksNET:~ $ export DISPLAY=127.0.0.1:0.0
pi@CodeGimmicksNET:~ $ echo $DISPLAY
127.0.0.1:0.0
pi@CodeGimmicksNET:~ $ xclock
Error: Can't open display: 127.0.0.1:0.0
pi@CodeGimmicksNET:~ $
```
### Your environment

- Hardware : Raspberry pi 3
- Operating system: Raspbian Strech

### Additional comments

{Please write here, if there is something more to tell}

**Comment by pihomeserver** [comment]
The script is defined to work on raspbian lite. Never tested on Raspbian.
Reasons could be many : x11 forwarding issue, bridge configuration, etc
