### ISSUE TITLE
Server certificate failed

### ISSUE THREAD

**Issue by Megafab** [pihomeserver/Kupiki-Hotspot-Script#111]
### Actual behavior

Bonjour,
Sur un Raspian Lite , j'ai le message suivant : 
fatal: unable to access 'https://github.com/pihomeserver/Kupiki-Hotspot-Script.git/': server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none

Alors que jusque ici cela marchait parfaitement.

### Expected behavior

{Please write here}

#### Configuration parameters (if changed in the script)

{Please write here}

#### Logs

```
// write log messages here, if possible
// like output of the script or system messages
// The more information you provide, the best answer you will get
```

### Your environment

- Hardware : Raspberry Pi3+
- Operating system: Raspbian Lite

### Additional comments

{Please write here, if there is something more to tell}

**Comment by pihomeserver** [comment]
Essayez un apt-get update puis apt-get upgrade et enfin de relancer le script

**Comment by Megafab** [comment]
Bonjour,

C'est pareil.
C'est une Raspbian que j'ai réinstallé, mis a jour.La semaine dernière cela fonctionnait parfaitement.

**Comment by Megafab** [comment]
Oups pardon de ma faute, il n'était pas à l'heure ...
