### ISSUE TITLE
PIN base authentication

### ISSUE THREAD

**Issue by bboy1983** [pihomeserver/Kupiki-Hotspot-Script#118]
Hi, how are you?..Thank you for your hardwork and effort to build this awesome project. anyways i want to use PIN based instead of Username & Password.
How can i change the Log-in page into PIN authentication?. Thank you very much.

**Comment by pihomeserver** [comment]
Hello. You can change the source of the portal that is located in the usr/share/nginx folder. 
Not sure how to perform that with a high security ... you can try to create a user with the pin code as the id, empty password that will be forced in the portal.
