### ISSUE TITLE
Batch users json request time out

### ISSUE THREAD

**Issue by droecoleman** [pihomeserver/Kupiki-Hotspot-Script#125]
batch users json request time out. 
take note i did not change anything. 
i also refer to other previous suggestions created issues.  But it did not help

**Comment by pihomeserver** [comment]
Please provide the result of ifconfig -a command to check ip allocation on all interfaces

**Comment by droecoleman** [comment]
![image](https://user-images.githubusercontent.com/37513813/43441028-f0cfac98-94cb-11e8-88a8-eb0feb27c810.png)

here it is.

**Comment by droecoleman** [comment]
![image](https://user-images.githubusercontent.com/37513813/43453902-ee24cd6c-94ed-11e8-82eb-caf7fd363068.png)



![image](https://user-images.githubusercontent.com/37513813/43453842-bd316e7c-94ed-11e8-8250-2016b8855a7c.png)

![image](https://user-images.githubusercontent.com/37513813/43454015-4a3e5a1e-94ee-11e8-9bc0-a2d7b4416e0d.png)


here it is.

**Comment by pihomeserver** [comment]
I Don't get where the issue occurs. In Dalo or the portal ?

**Comment by droecoleman** [comment]
im sorry the error occurs in the portal.

**Comment by pihomeserver** [comment]
And the message that you get from the portal ?
Do you see all the users in daloradius ?

**Comment by droecoleman** [comment]
yes i can see all the users  in daloradius. however when i try to log them in to the portal I always get the error json request time out

**Comment by pihomeserver** [comment]
Can you try with a user created manually with a clear password attribute ? The bath uses the user password attribute and it seems to not work as expected

**Comment by droecoleman** [comment]
i have done creating without attribute but still the error is there..

**Comment by pihomeserver** [comment]
Does chilli process running ?
You need at least one attribute cleartext-password to define the user  password.

**Comment by droecoleman** [comment]
yes it is running.. but freeradius  

![image](https://user-images.githubusercontent.com/37513813/43475984-f3e1893e-9529-11e8-8e3e-4d52ae7562e2.png)

**Comment by droecoleman** [comment]
freeradius is now running..

then this

![image](https://user-images.githubusercontent.com/37513813/43479174-51cea90c-9532-11e8-9404-1ec16d4f0e13.png)

**Comment by droecoleman** [comment]
![image](https://user-images.githubusercontent.com/37513813/43479272-93d417ec-9532-11e8-93b1-419b5731dbf4.png)

**Comment by pihomeserver** [comment]
Same here and should not be an issue
Try to create a user test with a check attribute "Cleartext-Password", operant set to ":=" and value to "test". Then you should be able to connect with username test and password test

**Comment by pihomeserver** [comment]
Are you sure that you stopped freeradius before running it again ? The message says that port 1700 is already used ...

**Comment by droecoleman** [comment]
yes, i stopped freeradius and that is the output

**Comment by pihomeserver** [comment]
After a reboot, is freeradius running ? Only freeradius is using the port 1700 so that means that you have multiple freeradius running and of course that's not the expected behavior.
You confirm using the Raspbian Lite and not the full Raspbian OS ?

**Comment by droecoleman** [comment]
i am now getting this

![image](https://user-images.githubusercontent.com/37513813/43481039-6f34b7b6-9537-11e8-9fe0-3fb59f63aaff.png)

**Comment by pihomeserver** [comment]
Keep that window open, then create the user as explained below
```
Try to create a user test with a check attribute "Cleartext-Password", operant set to ":=" and value to "test". Then you should be able to connect with username test and password test
```
And check the connectivity with the radtest command
```
radtest test test 127.0.0.1 1812 <my_secret_key>
```
The secret key can be found with the command 
```
cat /etc/freeradius/3.0/clients.conf | grep secret | grep -v '[\s]*#' | head -1 | cut -d '=' -f 2 | awk '{$1=$1};1'
```

**Comment by pihomeserver** [comment]
In addition : 

> It is important to understand the difference between the  User-Password
       and Cleartext-Password attributes.  The Cleartext-Password attribute is
       the "known good" password for the user.	Simply supplying  the  Cleart-
       ext-Password  to  the server will result in most authentication methods
       working.  The User-Password attribute is the password as  typed	in  by
       the  user  on  their  private  machine.	 The two are not the same, and
       should be treated very differently.  That is, you should generally  not
       use the User-Password attribute anywhere in the RADIUS configuration.

[Source](https://freeradius.org/radiusd/man/rlm_pap.txt)

Then why Daloradius is using User-Password instead Cleartext-password, i don't know why yet.

**Comment by desevensa** [comment]
@droecoleman : I realized about issue 87, if for some reason the install stops after freeradius get installed (Ctrl+c or power outage, or any other reason), Re-launch the script ends in the same error because in line 689 `sed -i "s/testing123/$FREERADIUS_SECRETKEY/g" /etc/freeradius/3.0/clients.conf` "testing123" already changed and those keys wont be the same. 
If you have to run again the script you must have this in mind to avoid that issue.

**Comment by pihomeserver** [comment]
@desevensa I will change that. Thank you

**Comment by droecoleman** [comment]
i did a fresh install, but then the problem now, the batch users are not recognized by the data base. if you  try using the batch add users, it will be created successful but it wont be recognize when the passwords not recognized
