### ISSUE TITLE
[Question]Can this instalation script be used with Raspberry Pi 2? 

### ISSUE THREAD

**Issue by magno23** [pihomeserver/Kupiki-Hotspot-Script#128]
As the title says, can i use this script to install the software on a RPi2?

**Comment by pihomeserver** [comment]
In theory yes if you are able to make your wifi dongle visible  from the network interfaces before starting the script execution. If it's the case then update the wifi driver if necessary and then run the script.

**Comment by pihomeserver** [comment]
Confirmed [here](https://github.com/pihomeserver/Kupiki-Hotspot-Script/issues/140#issuecomment-435715285)
