### ISSUE TITLE
change wifi part by an second ethernet port ?

### ISSUE THREAD

**Issue by lebphi** [pihomeserver/Kupiki-Hotspot-Script#132]
Hi,

i've bought an usb to ethernet adapter. My goal is to connect an powerful access wifi point to pihomeserver.
it is possible to parameter the install script for replace the wifi interface by the second ethernet adapter (eth01) ?

Or it is possible to do that after the installation ?

regards 

philippe

**Comment by pihomeserver** [comment]
You can define in the script the source (WAN) interface and the hotspot interface (LAN).
Then what i would do is to configure all the system first with your adapter, update parameters in the script and then run it.
Changing LAN/WAN parameters after is a little bit more complex
