### ISSUE TITLE
Access devices of the local network

### ISSUE THREAD

**Issue by Manifact** [pihomeserver/Kupiki-Hotspot-Script#137]
### Actual behavior

Hotspot users can't access any devices of the local Network

### Expected behavior

Hotspot users can acces specified devices of the local Network

I'd like to anable 2 devices of my local network to be accessible from hotspot users.
One device is a NAS and the other is a laser-cutter driven through a web-based software (http requests).
I think you adressed this problem in issue #119 but I don't know where to modify the "rules defined at lines 734-735" and what to insert in my iptables list. 

Thank you,

Thibault

**Comment by pihomeserver** [comment]
Hello
Try the solution [here](https://github.com/pihomeserver/Kupiki-Hotspot-Script/issues/119#issuecomment-403756715)
You have to change a parameter of Coova to allow local LAN access
