### ISSUE TITLE
Wlan0 - > hot-spot and wlan1 - > internet connection 

### ISSUE THREAD

**Issue by acujl** [pihomeserver/Kupiki-Hotspot-Script#142]
I'm trying to use a external wifi USB dongle as the internet access and wlan0 (wifi default on raspberry 3) as hot-spot . 

When I install raspian I can access the internet through my wifi dongle (wlan1) on the wifi interface list, set up password etc...

But when I install the script just appears "no interface network available"

No idea why this occurs 🤔

**Comment by pihomeserver** [comment]
Hello
Did you get any error message other than that ? What is the output of the list of interfaces ?

**Comment by acujl** [comment]
I went and installed everything again....
Before instalation the interfaces looked nominal, I could acess wifi on wlan0 and wlan1 (my adapter) etc.

During the instalation I had an error yes..
```

::: Activating the banner for SSH
:::
::: Creating Kupiki Admin folder for the database
::: Changing rights of the folder
::: Updating authentication plugin
::: Starting freeradius service
:::
::: Something went wrong with the last command. Please check the log file
:::
```
After this interfaces just died including eth0, I had to acess it remotly 
![whatsapp image 2018-11-01 at 10 28 58 am](https://user-images.githubusercontent.com/30632902/47846870-4d4b3080-ddc1-11e8-9d5a-aa0e4cc42776.jpeg)



[kupiki_hotspot.log](https://github.com/pihomeserver/Kupiki-Hotspot-Script/files/2538153/kupiki_hotspot.log)

**Comment by pihomeserver** [comment]
1) Did you changed the hotspot driver for your wifi interface if you don't use the built in adaptater ? There is a parameter for that in the script
2) Freeradius is not able to start. I guess the first steps should be
- Check if hostapd is able to start. Look if the process is running 
- If it runs then start coova using command `coova -f -d` (to be confirmed)
- If it runs then start freeradius using command `freeradius -X`
