### ISSUE TITLE
Unknown name "Access-Period"

### ISSUE THREAD

**Issue by macalimosa** [pihomeserver/Kupiki-Hotspot-Script#145]
#### Logs

```
(11) sql: ERROR: Failed to create the pair: Unknown name "Access-Period"
(11) sql: ERROR: Error parsing user data from database result
(11) sql: ERROR: Error retrieving check pairs for group client
```

### Your environment

- Hardware : Rasperberry pi 3 b+
- Operating system: Raspbian Sretch Full

### Additional comments

Would like to add attritube from daloradius profile but i got this errors when user trying to login.

**Comment by macalimosa** [comment]
Solved by creating sqlcounter accessperiod

**Comment by pihomeserver** [comment]
Hello

Can you please share the updates and where you made them ?

**Comment by macalimosa** [comment]
sure i add this code from /etc/freeradius/3.0/mods-available
