### ISSUE TITLE
How to access admin

### ISSUE THREAD

**Issue by jerpacs** [pihomeserver/Kupiki-Hotspot-Script#147]
### Actual behavior

just installed kupiki hotspot with admin enabled

### Expected behavior

where and how to open admin dashboard?

#### Configuration parameters (if changed in the script)

mariadb issues and need to do it manually

#### Logs

sorry, didn't enabled logs.
// write log messages here, if possible
// like output of the script or system messages
// The more information you provide, the best answer you will get
```

### Your environment

- Hardware : VBox
- Operating system: Ubuntu

### Additional comments

{Please write here, if there is something more to tell}

**Comment by pihomeserver** [comment]
Never tested on any VM.
URL to access Daloradius is displayed at the end of the execution of the script. The URL is the IP of the Rapsberry on default port 80
