### ISSUE TITLE
How can I get the original Coovachilli captive portal?

### ISSUE THREAD

**Issue by desevensa** [pihomeserver/Kupiki-Hotspot-Script#157]
### Actual behavior

Runs Ok with new Captive portal for wifi clients

### Expected behavior

Install the old-fashioned Captive portal

### Additional comments

I want make modifications for that code in HTML

**Comment by pihomeserver** [comment]
Not sure to understand. You want the default portal from Coova ?

**Comment by desevensa** [comment]
Yes, exactly that.

**Comment by pihomeserver** [comment]
Be sure that Haserl is installed and then update/replace following parameters in config file : 
```
HS_UAMSERVER=$HS_UAMLISTEN
HS_UAMUIPORT=4990
HS_UAMFORMAT=http://\$HS_UAMLISTEN:\$HS_UAMUIPORT/www/login.chi
HS_UAMHOMEPAGE=http://\$HS_UAMLISTEN:\$HS_UAMPORT/www/coova.html
```

**Comment by desevensa** [comment]
Thanks a lot. I will do it. :+1:

**Comment by desevensa** [comment]
@pihomeserver Thank you. I get it now the default coova portal.
