### ISSUE TITLE
Failed to restart hostapd.service: Unit hostapd.service is masked.

### ISSUE THREAD

**Issue by pankajdahilkar** [pihomeserver/Kupiki-Hotspot-Script#163]
while installing got this issue.

::: Restarting hostapd
Failed to restart hostapd.service: Unit hostapd.service is masked.
:::
::: Something went wrong with the last command. Please check the log file
:::

installing on Raspbian Stretch Lite.

**Comment by pihomeserver** [comment]
I have the same issue now with latest upgrade. I'm looking for a solution. Until then you can unmask the service and restart it manually. A reboot after that should then restart all
