### ISSUE TITLE
Mac address authentication

### ISSUE THREAD

**Issue by demperor13** [pihomeserver/Kupiki-Hotspot-Script#184]
Excuse me ..... is there any way to add a specific mac so that it bypasses login page and directly access the internet ..... 

i tried mac address authentication option in daloradius but it requires you to enter the mac address as a username ....

### Your environment

- Hardware : Raspberry pi 3
- Operating system: Raspbian Stretch lite

### Additional comments

{Please write here, if there is something more to tell}

**Comment by pihomeserver** [comment]
You have to activate the option in Coova in order to push the mac address to Freeradius as the username

**Comment by demperor13** [comment]
how can i do this ? 
Sorry for inconvinence but i am just a beginner

**Comment by pihomeserver** [comment]
In coova configuration file add `/etc/chilli/config`
```
HS_MACAUTH=on
HS_MACPASSWD=<what ever you want, but same than the one you set when you created the user>
```
So you have to create users with the same password for all

**Comment by demperor13** [comment]
Tried this method and still portal webpage is popping up whenever i tries to access the network .....

Searched in google for a while and found a solution by editing /etc/chilli/defaults file and adding the mac address i want and finally it worked ....

Thanks alot for this great project and for your rapid response to any issues
