### ISSUE TITLE
Incorrect User name password in admin login. 

### ISSUE THREAD

**Issue by uplsourav** [pihomeserver/Kupiki-Hotspot-Script#186]
### Actual behavior

{after running the script file. open the admin page. trying login with the user name password that I got at end of the script execution. but not able to login, getting an error.  "Incorrect USERNAME or  PASSWORD"}

**Comment by 0x290591** [comment]
Hi,
Try username : admin, password : admin 

Maksymilian

**Comment by uplsourav** [comment]
@0x290591  Thank this id works. able to log in.

closing this issue.
