### ISSUE TITLE
Docker-compose

### ISSUE THREAD

**Issue by OrbisTerrarumProLiberi** [pihomeserver/Kupiki-Hotspot-Script#190]
### Actual behavior

Error install
### Expected behavior

Installation completed.

#### Configuration parameters (if changed in the script)

none
#### Logs

```
::: Build the Docker image of Portal backend
-bash: /usr/local/bin/docker-compose: No such file or directory
:::
::: Something went wrong with the last command. Please check the log file

### Your environment

- Hardware : Raspberry Pi 3
- Operating system: Rasbian Buster Desktop

### Additional comments

Any help will be much appreciated. Thanks

**Comment by pihomeserver** [comment]
Quick search in the issues list : #190

**Comment by OrbisTerrarumProLiberi** [comment]
fixed by eding script.
su - kupiki -c "cd /home/kupiki/kupiki-portal-backend && /usr/local/bin/docker-compose build"
to
su - kupiki -c "cd /home/kupiki/kupiki-portal-backend && /usr/bin/docker-compose build"

must have not noticed it earlier. Thanks!
