### ISSUE TITLE
Cant access daloradius

### ISSUE THREAD

**Issue by OrbisTerrarumProLiberi** [pihomeserver/Kupiki-Hotspot-Script#191]
### Actual behavior

<ipaddress>/daloradius gives 404 Not Found
<ipaddress> 502 Bad Gateway
<ipaddress>:8080 refused to connect
### Expected behavior

Daloradius web interface 

#### Configuration parameters (if changed in the script)

{Please write here}

#### Logs

Installation was successful

### Your environment

- Hardware : Raspberry Pi 3
- Operating system: Raspbian lite

### Additional comments

Any help will much appreciated. Thanks!

**Comment by pihomeserver** [comment]
Check nginx logs in order to have more details and crosscheck with its configuration

**Comment by OrbisTerrarumProLiberi** [comment]
updated php.ini
added: cgi.fix_pathinfo=0

changed /etc/nginx/sites-available
from
 fastcgi_pass unix:/var/run/php/php7.0-fpm.sock;
to
 fastcgi_pass unix:/var/run/php/php7.3-fpm.sock

**Comment by pihomeserver** [comment]
Thank you
