### ISSUE TITLE
[Question]  route traffic to a VPN?

### ISSUE THREAD

**Issue by DickThomas** [pihomeserver/Kupiki-Hotspot-Script#197]
hiya 
I've literary no idea how IP tables works but would it be possible to set this up to route
either everyone or a certain set of users via a VPN or TOR?

Sorry I know this Question is totally out of the scope of issues tab but I didn't wish to spend 
days learning IP tables.
and find it wasn't possible :) 

many thanks

**Comment by pihomeserver** [comment]
Should be possible via a POSTROUTING iptable rule in the ifup script. Try to look at your prefered search engine as i am not a master of the tool

**Comment by DickThomas** [comment]
thank you,
I wasn't sure if the portal interface would cause issues.
I shall Google the night away :)
