### ISSUE TITLE
what is "jq" command?

### ISSUE THREAD

**Issue by chivarpilones** [pihomeserver/Kupiki-Hotspot-Script#215]
what is "jq" command?

### Actual behavior

::: Activating CoovaChilli
::: Creating CoovaChilli at /etc/chilli/config
::: Configure MAC address authentication (1/2)
::: Configure MAC address authentication (2/2)
::: Activating CoovaChilli on boot
::: Creating configuration file for hostapd
::: Configuring hostapd
::: Installing Daloradius in Nginx folder
::: Loading daloradius configuration into MySql
::: Drop freeradius tables created by Daloradius to reload the Freeradius 3.0 version
::: Reload original Freeradius schema
::: Creating users privileges for localhost
::: Granting users privileges
::: Configuring daloradius DB user name
::: Configuring daloradius DB user password
::: Configuring daloradius DB proxy configuration file
::: Configuring daloradius DB proxy path
::: Building NGINX configuration (default listen port : 80)
::: Building NGINX configuration for the portal (default listen port : 80)
::: Activating portal website
::: Installing the portal in Nginx folder
::: Updating Captive Portal configuration file - Register host
./pihotspot.sh: line 1024: jq: command not found

### Expected behavior

{Please write here}

#### Configuration parameters (if changed in the script)

{Please write here}

#### Logs

```
// write log messages here, if possible
// like output of the script or system messages
// The more information you provide, the best answer you will get
```

### Your environment

- Hardware : {Please write here}
- Operating system: {Please write here}

### Additional comments

{Please write here, if there is something more to tell}

**Comment by pihomeserver** [comment]
https://jqlang.github.io/jq/
