### ISSUE TITLE
JSON request time out

### ISSUE THREAD

**Issue by vanrion** [pihomeserver/Kupiki-Hotspot-Script#37]
there's was an error when redirecting in Portal and also  when trying to login with this new Kupiki-Hotspot..

**Comment by pihomeserver** [comment]
Can you please check at the html content of /usr/share/nginx/portal/index.html and be sure that the IP of the coova server is well set ?
`chilliController.host = "192.168.10.1";`

**Comment by pihomeserver** [comment]
I have just tried from scratch with default parameters within the script and i do not have the issue

**Comment by vanrion** [comment]
yes it is. maybe i should try another fresh installation.

**Comment by vanrion** [comment]
it redirect in this ip 192.168.0.34:9000/?index.html...something like that, which is my raspberry pi local IP.

**Comment by pihomeserver** [comment]
Yes that could be the reason even if i tried to not hardcode IP address
The IP in the HTML should be the WAN interface with the port 9000 (not the hotspot IP)
You could reach it from any browser on the same network

**Comment by vanrion** [comment]
ok, i just do fresh installation with default parameter and it's working.. :+1: 
Now, i wanted to add another page for Time Remaining. any idea Sir?.

**Comment by pihomeserver** [comment]
If you use http://status in the  location bar you should have some useful information
i plan to use the same page to display that information if the system detects that you are connected

**Comment by vanrion** [comment]
@pihomeserver  I have this error again. 

![img_3718](https://user-images.githubusercontent.com/17348802/27982606-e3747f68-635a-11e7-92d7-e94aee17c25c.PNG)

**Comment by pihomeserver** [comment]
Arf that's strange. Maybe it's due to the custom ip. Did you try to run coova and freeradius manualy to see possible error message ?
I will try to run the script on a frresh install. Can you please provide your custom parameters to use the same ?
