### ISSUE TITLE
Create a ready-to-use distro

### ISSUE THREAD

**Issue by pihomeserver** [pihomeserver/Kupiki-Hotspot-Script#42]
I think that some people could be interested to get a hotspot without calling the script if they agree to use default configuration. Then generating an img file ready to be installed on a 2Gb sd card could be provided.

What is the best place to store the file ?

**Comment by pihomeserver** [comment]
Implemented

**Comment by Cocophotos** [comment]
Hi,

Thanks a lot for the marvelous job.

Could you give the username & password to access the distro through SSH, please?

Best,

-- 
Corentin

**Comment by pihomeserver** [comment]
User pi and password pihotspot. Same password for root. Try to update the portal as it's not the latest version installed
