### ISSUE TITLE
Make installation of Haserl optional

### ISSUE THREAD

**Issue by pihomeserver** [pihomeserver/Kupiki-Hotspot-Script#47]
Haserl is needed only in case of using the default coova chilli web portal.
In order to improve installation time, haserl could be disabled by default but activable in the configurable part of the script

**Comment by mclaassen** [comment]
I noticed that haserl is also part of the packages that are installed. After that you are installing a (newer) version of haserl and compile that one. Is the standard one not sufficient in that case?

**Comment by pihomeserver** [comment]
Yes i have to remove the one in the dependencies and make optional the build of the other one

**Comment by pihomeserver** [comment]
v1.2 (force coova chilli installation without dependencies check)
