### ISSUE TITLE
Implement a login message over ssh

### ISSUE THREAD

**Issue by pihomeserver** [pihomeserver/Kupiki-Hotspot-Script#49]
Use of motd to add a reminder of main parameters of the system

to be confirmed if useful and secured

**Comment by vanrion** [comment]
@pihomeserver Huge improvement so far very nice..
hope we can add Status Page, i'm wondering if we can still use or incorporate the Coova Chilli Status page?.

**Comment by pihomeserver** [comment]
Basic message added. Monitoring is included in the administration website
