### ISSUE TITLE
Full distro credentials

### ISSUE THREAD

**Issue by africanalex** [pihomeserver/Kupiki-Hotspot-Script#51]
I am unable to log in to daloradius or ssh to the raspberry pi having used the full distro, please could you provide the login details

**Comment by pihomeserver** [comment]
Hello
Did you tried user : pi / password : pihotspot ?

**Comment by pihomeserver** [comment]
Better to use a fresh Raspbian Lite then use the script to get the latest version

**Comment by africanalex** [comment]
on it, thanks
