### ISSUE TITLE
Login error using the raspbian image

### ISSUE THREAD

**Issue by aqt01** [pihomeserver/Kupiki-Hotspot-Script#58]
I downloaded the image and burned it in an SD. But i get login error using the credentials:
user: pi
Password: pihotspot

[Link](https://drive.google.com/file/d/0B5CzDtjmXSaySVNPZ1A1VkYtVFk/view)

i'm missing something?

**Comment by pihomeserver** [comment]
Can you please try user pi and password raspbian ?

**Comment by huseyinergen** [comment]
Yes. it is correct. Please change the information on the web page. This image file does not have pi/pıhotspot info....

**Comment by pihomeserver** [comment]
Done
