### ISSUE TITLE
Help wanted - Administration portal pre-alpha testing

### ISSUE THREAD

**Issue by pihomeserver** [pihomeserver/Kupiki-Hotspot-Script#59]
Hello,

I'm looking for 1 or 2 persons that would have enought time to help me in the testing of the administration portal that i'm creating for the hotspot.
For now don't expect so mush but with time functionalities should be :
- System management : 
   - basic monitoring like cpu, memory, uptime, services
   - basic administration : stop/start services, reboot, halt, update
- Hostpot management
    - Change hostapd configuration like hotspot name, driver, etc
    - Change coova configuration like ip range, dhcp, etc
- Hotspot portal management
    - Change background picture
    - Change few parameters like terms and condition
- Daloradius replacement
    - Provide a basic user management interface (create, edit, check, revoke, attributes, etc.)
    - Provide some other functions (vounchers, nas management)
    - Statistics to be defined

Technologies : Angular 1.6 + NodeJS
The first alpha has been tested on the Pi and seems to work great

Any volunteers ?

**Comment by vanrion** [comment]
Hi, where can i download the image to test?

**Comment by pihomeserver** [comment]
Can you please send me an email on my gmail mailbox (pihomeser at gmail dot com)

**Comment by jeebee2013** [comment]
hi 
ok for testing
en plus on pourra échanger en Francais :-)

**Comment by pihomeserver** [comment]
Salut
Peux tu m'envoyer un email (celui plus haut)? Pour éviter de polluer le flux
