### ISSUE TITLE
Oops, something went wrong with the configuration file

### ISSUE THREAD

**Issue by travuga77** [pihomeserver/Kupiki-Hotspot-Script#64]
Good afternoon!

After 1.4.4 update pihotspot.sh script cannot find configuration.json file at "Updating Captive Portal" step. As I understand, Kupiki-Hotspot-Portal is updating right now, so configuration file will appear later, isn't it?

**Comment by pihomeserver** [comment]
My fault my fault ! I forgot yesterday to push the configuration.json file in the portal GitHub !
You can download it manually or restart the script

**Comment by fernas** [comment]
Now I'm getting an error on "Cloning daloradius project".

**Comment by pihomeserver** [comment]
more details please !

**Comment by fernas** [comment]
On Log:

fatal: unable to access 'https://github.com/lirantal/daloradius.git/': Could not resolve host: github.com.

When I start this script, my dhcp setting are not working anymore and my raspberry pi lost its internet connection.

**Comment by pihomeserver** [comment]
Strange as the script is not updating any DNS information. But the /etc/network/interfaces file is updated to configure the WLAN interface only. Can you please share the content of this file ?

**Comment by travuga77** [comment]
my problem is solved, thanks!
