### ISSUE TITLE
Docker Image

### ISSUE THREAD

**Issue by droberin** [pihomeserver/Kupiki-Hotspot-Script#68]
Hello, folks.
I'm intended to use this software. Is there any official Docker Image?
If not, I might help with that.

**Comment by pihomeserver** [comment]
Hi
Unfortunatly no. First i don't master Dokerfile and second i don't know how to use the Wifi hardware to build the hotspot within a docker container. 
So sure that help is fully welcome ! I would love to test that !

**Comment by pihomeserver** [comment]
Can be reopened if the need is still required
