### ISSUE TITLE
Redirect after login.

### ISSUE THREAD

**Issue by bobdmagic** [pihomeserver/Kupiki-Hotspot-Script#7]
When you log into the hotspot it directs you to a successful login page. Then after a set time it directs you to another page. I would like prefer that it directs you to the google search page when it leaves the successful login page.  Also, I changed the title in the title file but it stayed the same after reboot. Where else do I change the title?
Thanks in advance for your reply.

**Comment by pihomeserver** [comment]
Not sure but maybe you have to rebuild the www folder after each change (you speack about title.tmpl ?)
I still have to work on these customizations. If you have advices they are welcome ;-)

**Comment by pihomeserver** [comment]
In the latest version, the portal used is in html with a redirection on success that you can customize
