### ISSUE TITLE
script stuck using berryboot

### ISSUE THREAD

**Issue by mickrow** [pihomeserver/Kupiki-Hotspot-Script#79]
hi.
i am not sure how to address this and how to add crucial information, but the script works smooth on latest stretch (lite & full) if it's the only OS on the RPi. it's an awesome help and i love it.
using berryboot however, it fails. it might be a timeout problem?
i do not want to use the existing jessie based berryboot image (which works).

```
::: Creating freeradius database
ERROR 1133 (28000) at line 1: Can't find any matching row in the user table
ERROR 1396 (HY000) at line 1: Operation DROP USER failed for 'radius'@'localhost
```

any chance to have a deeper look into it from your side?

thanks!

**Comment by pihomeserver** [comment]
Hi
These messages are "normal" in case of first install. It tries to delete the radius user to reinstall it.

What is the last log that you were able to see (you can check /var/log/kupiki file) ? It will help to get the last executed command

**Comment by mickrow** [comment]
thanks for your quick reply.
last log entry was "Checking freeradius configuration"...

```
::: Bug fix for SQL dialect once SQL Counters are activated
::: Updating inner-tunnel configuration (1)
::: Updating inner-tunnel configuration (2)
::: Updating freeradius default configuration (1)
::: Updating freeradius default configuration (2)
::: Checking freeradius configuration
::: 
::: Something went wrong with the last command. Please check the log file
::: 
```

**Comment by pihomeserver** [comment]
Can you please run from command line as root :
freeradius -C
And paste the result ?

**Comment by mickrow** [comment]
it goes straight back to prompt without any console output. radius.log comes up with this:
```
Wed Feb  7 15:18:12 2018 : Info: Debugger not attached
Wed Feb  7 15:18:12 2018 : Info: rlm_sql (sql): Driver rlm_sql_mysql (module rlm_sql_mysql) loaded and linked
Wed Feb  7 15:18:12 2018 : Error: Unable to check file "/etc/ssl/private/ssl-cert-snakeoil.key": Permission denied
Wed Feb  7 15:18:12 2018 : Error: rlm_eap_tls: Failed initializing SSL context
Wed Feb  7 15:18:12 2018 : Error: rlm_eap (EAP): Failed to initialise rlm_eap_tls
Wed Feb  7 15:18:12 2018 : Error: /etc/freeradius/3.0/mods-enabled/eap[14]: Instantiation failed for module "eap"
```

**Comment by pihomeserver** [comment]
Strange with the ssl issue. Don't know why it looks for a certificate. Did you activated the option in the script ?
I will check that once at home

**Comment by mickrow** [comment]
yeah, thats the funny thing. only changed hostname & passwords/certificates. all other options untouched (no SSL). all settings work perfectly on solitary OS unless you boot a fresh stretch out of berryboot. so it must have something to do with it. squashfs might be slower, content of /boot is different.... i have no angle and am clueless, thats why i opened this issue :D

thanks for your time and checking into it.

**Comment by pihomeserver** [comment]
Script confirmed to not work with a BerryBoot (and possible issues with Noobs - to be confirmed)
