### ISSUE TITLE
Dhcpcd failed on all interfaces

### ISSUE THREAD

**Issue by xnhn** [pihomeserver/Kupiki-Hotspot-Script#82]
Hi

Here's my issue : 
The script installation works perfectly on a brand new Raspbian Lite.
At the end, I can connect on the wifi hotspot as expected and go on the login page.
However, after a reboot, the dhcpcd.service shows : failed on all interfaces. At this moment, I still can connect to the hotspot but can't reach the login page anymore.

Do you have any idea where i missed something ? 
Thanks

**Comment by pihomeserver** [comment]
Can you please share the error message of dhcpd ? Without it, it's difficult to investigate

**Comment by xnhn** [comment]
Hi, 
Thanks for your fast reply.

The error message is showned during the booting sequence :
[FAILED] Failed to start dhcpcd on all interfaces.

This is the only error code i have.

**Comment by pihomeserver** [comment]
Try to start it manually and get the error message from commands provided in the console

**Comment by xnhn** [comment]
I found the issue origin. It's from the Freebox V6 router.
Thanks anyway
