### ISSUE TITLE
how use with static ip

### ISSUE THREAD

**Issue by trexment** [pihomeserver/Kupiki-Hotspot-Script#83]
Hi, can use with the static ip in ETH0? because don't find this option.

Thanks

**Comment by pihomeserver** [comment]
Hi this is not an option. You can change your configuration before or after the installation
Tell me if this is a requirement within the installation process

**Comment by reigelgallarde** [comment]
I think it's not a problem using static IP on eth0.
I'm using static IP for the rpi from my router's dhcp settings ...

**Comment by trexment** [comment]
Ok, i'm finde the solution, Change the configuration in the file /etc/network/interfaces and put the static IPs.  Thank you very much!!.

**Comment by trexment** [comment]
Yes, but my router don't active dhcp
