### ISSUE TITLE
HotSpot

### ISSUE THREAD

**Issue by papanas12** [pihomeserver/Kupiki-Hotspot-Script#84]
Hi can u please explain how to change :The design of the portal can be easily modified for anyone who has knowledge in HTML and Javascriptconfiguration  where do u do that

Thank u

**Comment by pihomeserver** [comment]
Hello
The portal content is from the repo https://github.com/Kupiki/Kupiki-Hotspot-Portal
Once all installed you will find the source in the folder /usr/share/nginx/
Update sources for the design you want in that folder

**Comment by papanas12** [comment]
Hello

Thank u very much great
Le Lundi, Février 26, 2018 18:08 GMT, Pi Home Server <notifications@github.com> a écrit:
 
Hello
The portal content is from the repo https://github.com/Kupiki/Kupiki-Hotspot-Portal
Once all installed you will find the source in the folder /usr/share/nginx/
Update sources for the design you want in that folder
—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or mute the thread. 


--
Cordialement
PAPANASTASSIOU Alexandre
